import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import fs from "node:fs";
import path from "node:path";

const GALLERY_DIR = path.resolve("public/Gallery");
const OUT_FILE = path.resolve("src/gallery.auto.js");
const IMAGE_RE = /\.(webp|jpe?g|png|gif|avif)$/i;

/** Guess a short category from the filename. */
function categoryFromName(name) {
  const n = name.toLowerCase();
  if (/bus|transport|van/.test(n)) return "Transport";
  if (/gate|campus|building|entrance|class|room/.test(n)) return "Campus";
  if (/sport|play|field|game/.test(n)) return "Activities";
  return "School life";
}

/** Turn a filename into readable alt text. */
function altFromName(name) {
  const base = name.replace(/\.[^.]+$/, "");
  const cleaned = base
    .replace(/[_-]+/g, " ")
    .replace(/\s*\(\d+\)\s*/g, " ")
    .replace(/gemini generated image\s*/gi, "")
    .replace(/\s+/g, " ")
    .trim();
  if (!cleaned || cleaned.length < 3) return "Hill Springs Academy, Maua";
  // If still looks like a hash/id, use a generic label
  if (/^[a-z0-9]{8,}$/i.test(cleaned.replace(/\s/g, ""))) {
    return "Hill Springs Academy school life, Maua";
  }
  return `${cleaned} — Hill Springs Academy, Maua`;
}

function encodeGalleryPath(filename) {
  // Encode only the file name so spaces and special chars work in URLs
  return "/Gallery/" + encodeURIComponent(filename);
}

function scanGallery() {
  if (!fs.existsSync(GALLERY_DIR)) {
    fs.mkdirSync(GALLERY_DIR, { recursive: true });
  }
  const files = fs
    .readdirSync(GALLERY_DIR)
    .filter((f) => IMAGE_RE.test(f) && !f.startsWith("."))
    .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));

  const list = files.map((f) => ({
    src: encodeGalleryPath(f),
    alt: altFromName(f),
    cat: categoryFromName(f),
    file: f,
  }));

  const body =
    "// AUTO-GENERATED by vite.config.js — do not edit by hand.\n" +
    "// Drop image files into public/Gallery/ and restart or rebuild.\n" +
    `export const GALLERY_AUTO = ${JSON.stringify(list, null, 2)};\n`;

  const prev = fs.existsSync(OUT_FILE) ? fs.readFileSync(OUT_FILE, "utf8") : "";
  if (prev !== body) {
    fs.writeFileSync(OUT_FILE, body);
    console.log(`[gallery-auto] ${list.length} image(s) → src/gallery.auto.js`);
  }
  return list;
}

function galleryAutoPlugin() {
  return {
    name: "gallery-auto",
    buildStart() {
      scanGallery();
    },
    configureServer(server) {
      scanGallery();
      try {
        server.watcher.add(GALLERY_DIR);
      } catch {
        /* ignore */
      }
      const rescan = (file) => {
        if (!file || !String(file).includes(`${path.sep}Gallery`)) return;
        scanGallery();
        // Soft-reload so the browser picks up the new module
        server.ws.send({ type: "full-reload" });
      };
      server.watcher.on("add", rescan);
      server.watcher.on("unlink", rescan);
      server.watcher.on("change", rescan);
    },
  };
}

// Generate once when this config is loaded (covers tooling that imports config)
scanGallery();

export default defineConfig({
  plugins: [react(), galleryAutoPlugin()],
});
