/* Blog articles — keep slugs stable for existing links */
export const BLOG_POSTS = [
  {
    slug: "cbe-at-home-learning-beyond-the-classroom",
    title: "How Parents Can Support Competency-Based Education (CBE) at Home in Kenya",
    date: "October 2, 2026",
    intro: "Practical ways parents and guardians can reinforce Kenya’s Competency-Based Education at home through conversation, reading, household activities, reflection and positive routines. A guide for families in Maua, Igembe South, Meru County and across Kenya.",
    sections: [
      ["What CBE means for learning at home", "Competency-Based Education is concerned not only with what a learner remembers, but also with how they use knowledge, skills, values and attitudes in meaningful situations. Families do not need expensive learning equipment to support this. Everyday experiences—asking questions, explaining choices, measuring ingredients, caring for plants and reading together—can help children practise communication, critical thinking, creativity and collaboration. Parents should follow the learner’s current school guidance and avoid turning home into a second classroom filled with pressure."],
      ["Use ordinary household activities as learning opportunities", "A trip to the market can involve estimating quantities, comparing prices, checking change and discussing needs versus wants. Cooking can practise measurement, sequencing, hygiene and reading instructions. Gardening can prompt observation of soil, water, sunlight and plant growth. Invite the child to predict what may happen, explain the steps and reflect on what worked. Keep activities safe and age-appropriate; the learning comes from participation and conversation, not from making every task feel like an examination."],
      ["Build language and literacy through conversation", "Talk with children in the languages your family uses comfortably, and encourage them to explain their thinking. Ask open questions such as “What did you notice?”, “How could we find out?” and “What might you try next?” Storytelling, describing a journey, retelling a lesson and discussing a news item suitable for the child’s age all strengthen vocabulary and expression. Give learners time to answer instead of completing their sentences for them."],
      ["Make reading a predictable family habit", "Choose a regular reading time that fits family life. Younger children can look at picture books, identify objects, predict what happens next and listen to an adult read aloud. More confident readers can take turns reading paragraphs and discuss the main idea. Ask what happened, why a character acted as they did and how the story connects to real life. Keep the tone encouraging so reading remains a shared pleasure rather than a test."],
      ["Support reflection without overloading homework", "After a lesson or activity, invite the child to share one thing they learned, one challenge they met and one question they still have. Short written notes, drawings or oral summaries can help. Avoid adding large amounts of extra work beyond what the school has assigned. Rest, play and family time also support healthy development and readiness to learn."],
      ["Partner with the school", "When you are unsure about expectations, contact the class teacher or the school office. Share observations about what helps your child learn and ask how home practice can align with classroom goals. Attendance, punctuality, completed assignments and respectful communication all support progress under CBE."]
    ],
    closing: "For school-specific guidance on homework, assessment and learner support, contact Hill Springs Academy through the official channels on this website. Families in Maua and Igembe South are welcome to enquire about current programmes and admission information."
  },
  {
    slug: "reading-together-builds-confident-learners",
    title: "Reading Together Builds Confident Learners",
    date: "October 2, 2026",
    intro: "How families can support reading at home in Kenya, including simple routines that can work in busy households.",
    sections: [
      ["Why reading at home matters", "Reading supports learning across subjects because children use language to understand instructions, explain ideas and make sense of information. A child may decode words accurately yet still need help explaining what a passage means. Home reading can build fluency, vocabulary, comprehension and confidence when it is calm, regular and matched to the learner’s current ability. The aim is progress, not comparison with siblings or classmates."],
      ["Choose the right reading material", "Start with text the learner can read with reasonable success, then gradually introduce new vocabulary and longer passages. Stories, graded readers, poems, school-approved texts, labels, simple instructions and age-appropriate informational passages can all be useful. Allow children to choose from suitable options. If a book is so difficult that every line becomes a struggle, read it together or select an easier text and return to it later."],
      ["Use a short daily reading routine", "Set aside a predictable period—perhaps after a meal or before bedtime—depending on the household schedule. A useful session may include a few minutes of independent reading, a short read-aloud and a conversation about meaning. Younger learners benefit from hearing fluent reading and joining in with repeated phrases. Older learners can read silently, then summarise the main idea and identify one question they still have."],
      ["Teach comprehension with before, during and after questions", "Before reading, look at the title and ask what the text might be about. During reading, pause to clarify a confusing sentence or predict what may happen next. Afterwards, invite the child to retell the passage in their own words, describe a character’s decision, identify the main point or connect the text to an experience. Avoid turning every page into a quiz; conversation should help the learner make meaning."],
      ["Grow vocabulary without rote overload", "When an unfamiliar word appears, first use the surrounding sentence or picture to guess its meaning. Explain the word simply, say it aloud and make a new sentence together. Revisit useful words in later conversations. A small number of words understood deeply and used correctly is more valuable than copying a long list without comprehension. Encourage reading in the languages used at home and school as appropriate."],
      ["Keep reading positive", "Celebrate effort and improvement. If a child becomes frustrated, shorten the session, share the reading or switch to a more suitable book. Reading should strengthen confidence. If concerns persist, speak with the teacher so school and home can support the learner consistently."]
    ],
    closing: "For reading materials linked to your child’s level, check the Resources page on this website or ask the class teacher for recommended practice. Contact Hill Springs Academy for school-specific advice."
  },
  {
    slug: "why-play-matters-in-early-learning",
    title: "Why Play Matters in Early Learning",
    date: "October 2, 2026",
    intro: "Play is not a break from learning in the early years—it is one of the main ways young children build language, coordination, social skills and problem-solving.",
    sections: [
      ["Play supports foundational development", "Through play, children explore materials, test ideas, practise movement and learn how to share space and attention with others. Pretend play develops language and imagination. Construction play supports spatial thinking and persistence. Outdoor play builds strength, balance and confidence. These experiences complement structured classroom activities in Kindergarten and Pre-Primary."],
      ["Types of play families can encourage", "Simple materials are enough: blocks, bottles, cloth, balls, crayons, safe household objects and outdoor spaces. Encourage free play where the child leads, as well as guided play where an adult joins to model language or introduce a gentle challenge. Songs, rhymes, clapping games and storytelling also count as rich learning experiences."],
      ["Balance screen time with active play", "Screens can offer useful educational content when chosen carefully, but they should not replace hands-on play, outdoor activity and face-to-face conversation. Set clear limits that fit your household and prioritise sleep, movement and interaction. When children do watch educational videos, talk about what they saw afterwards."],
      ["Connect play with school learning", "Ask your child what they enjoyed at school and extend it at home—drawing shapes, sorting objects, counting steps or acting out a story. Keep activities short and joyful. Avoid turning every game into a formal lesson; the goal is curiosity and confidence."],
      ["Safety and supervision", "Choose age-appropriate materials, supervise as needed and set clear boundaries for outdoor play. A safe environment allows children to take reasonable risks, such as climbing or balancing, while adults remain attentive."]
    ],
    closing: "Hill Springs Academy values play as part of a balanced early-learning programme. For questions about Kindergarten or Pre-Primary, contact the admissions office."
  },
  {
    slug: "helping-children-build-healthy-study-habits",
    title: "Helping Children Build Healthy Study Habits",
    date: "October 2, 2026",
    intro: "Practical routines that help primary learners organise work, revise effectively and balance study with rest and play.",
    sections: [
      ["Create a simple, consistent study space", "A quiet corner with adequate light, a flat surface and the materials needed for the task reduces distraction. The space does not need to be elaborate. Keep pencils, books and a water bottle nearby so the learner can begin without searching for supplies."],
      ["Agree on a realistic routine", "Choose a regular time for homework or revision that fits family life—after a short break from school is often better than immediately before bed. Keep sessions age-appropriate in length. Younger learners may work best in short blocks with movement breaks; older learners can gradually extend focused time."],
      ["Teach active revision instead of only rereading", "After reading a section, close the book and ask the learner to explain the main idea, solve a similar example or write a few points from memory. Then reopen the material to check and correct misunderstandings. Flashcards, oral questions, diagrams and teaching a concept to a family member can make revision more active. Keep questions supportive and suitable for the topic and grade."],
      ["Support literacy and mathematics in everyday life", "Reading instructions, writing a shopping list, estimating quantities, checking change, telling time and discussing measurements can reinforce classroom learning. These activities are not replacements for assigned work, but they help children see how knowledge is used. Invite the learner to explain their method rather than focusing only on whether the final answer is correct."],
      ["Respond constructively when a child struggles", "Repeated difficulty may mean the child needs a different explanation, more practice, rest or a conversation with the teacher. Avoid labels such as lazy or clever; describe the specific effort or challenge instead. Ask what part feels confusing and work through one example together. If a learner consistently cannot complete work independently, communicate with the school to understand expectations and possible support."],
      ["Balance study with sleep, play and wellbeing", "Children need rest, movement, relationships and unstructured time as well as academic practice. A schedule that removes play or sleep to add more revision may be counterproductive for wellbeing. Keep routines age-appropriate, include breaks and notice signs of fatigue or distress. Encourage questions and mistakes as normal parts of learning, not reasons for shame."],
      ["Build independence one responsibility at a time", "Begin with one manageable responsibility, such as packing a reading book, checking a homework diary or choosing which task to start. Once the child can do it reliably, add another. Praise planning, persistence and asking for help appropriately. A good study routine is not simply a parent supervising every minute; it is a gradual transfer of responsibility to the learner."]
    ],
    closing: "For school-specific homework expectations, assessment guidance and learner support, communicate directly with the teacher or admissions office. Families in Maua and Igembe South can use the school’s official contact channels for current information."
  }
];
