// AUTO-GENERATED by vite.config.js — do not edit by hand.
// Drop image files into public/Gallery/ and restart or rebuild.
export const GALLERY_AUTO = [
  {
    "src": "/Gallery/Gemini_Generated_Image_41vrfl41vrfl41vr.webp",
    "alt": "Hill Springs Academy school life, Maua",
    "cat": "School life",
    "file": "Gemini_Generated_Image_41vrfl41vrfl41vr.webp"
  },
  {
    "src": "/Gallery/Gemini_Generated_Image_c99nfoc99nfoc99n%20(1).webp",
    "alt": "Hill Springs Academy school life, Maua",
    "cat": "School life",
    "file": "Gemini_Generated_Image_c99nfoc99nfoc99n (1).webp"
  },
  {
    "src": "/Gallery/school-bus.webp",
    "alt": "school bus — Hill Springs Academy, Maua",
    "cat": "Transport",
    "file": "school-bus.webp"
  },
  {
    "src": "/Gallery/school-gate.webp",
    "alt": "school gate — Hill Springs Academy, Maua",
    "cat": "Campus",
    "file": "school-gate.webp"
  }
];
